CLASS zpg_cl2 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun .

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpg_cl2 IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
out->write( 'holand2' ).
  ENDMETHOD.
ENDCLASS.
